import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(process.env.LAB_PLAYWRIGHT_ROOT?resolve(process.env.LAB_PLAYWRIGHT_ROOT,'package.json'):import.meta.url);
const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,...(process.env.LAB_BROWSER_PATH?{executablePath:process.env.LAB_BROWSER_PATH}:{channel:'chrome'})});
const context=await browser.newContext({viewport:{width:1280,height:900}});
const page=await context.newPage();page.on('dialog',d=>d.accept());
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const checks=[];const url=process.env.LAB_QA_URL||'http://127.0.0.1:4173';const key='ai-infra-lab.progress.v1';
const evidence='已完成文件创建和运行，保存了原始测试结果，并能独立解释输入、输出与错误处理。';
try{
 await page.goto(url);await page.getByRole('button',{name:'打开学习任务'}).click();
 await page.locator('#evidence').fill(evidence);await page.locator('a[data-view=resources]').click();
 await page.locator('a[data-view=learn]').click();await page.getByRole('button',{name:'打开学习任务'}).click();assert.equal(await page.locator('#evidence').inputValue(),evidence);
 await page.getByRole('button',{name:'记录为学习中'}).click();await page.getByRole('status').filter({hasText:'学习状态已保存'}).waitFor();checks.push('unsaved evidence survives internal navigation');
 await page.locator('a[data-view=resources]').click();
 await page.locator('#search').evaluate(el=>{window.imeInput=el;el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.value='动';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true,data:'动'}));});
 assert.equal(await page.evaluate(()=>window.imeInput===document.querySelector('#search')),true);
 await page.locator('#search').evaluate(el=>{el.value='动手';el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'动手'}));});
 assert.equal(await page.locator('#search').inputValue(),'动手');assert.equal(await page.locator('article.resource').count(),1);checks.push('Chinese composition preserves input until commit');
 await page.goto(url+'/#__proto__');await page.getByRole('heading',{name:'把知识变成工程能力'}).waitFor();checks.push('unknown prototype-shaped route falls back safely');
 const second=await context.newPage();second.on('dialog',d=>d.accept());await second.goto(url+'/#map');await second.locator('.node[data-node=arithmetic]').click();await second.locator('#evidence').fill('第二个标签页的未保存说明');
 await page.getByRole('button',{name:'打开学习任务'}).click();await page.locator('#evidence').fill(evidence);await page.getByRole('button',{name:'提交成果记录'}).click();
 await second.waitForFunction(()=>JSON.parse(localStorage.getItem('ai-infra-lab.progress.v1')).records.computer.status==='submitted');
 assert.equal(await second.locator('#evidence').inputValue(),'第二个标签页的未保存说明');
 await second.getByRole('button',{name:'记录为学习中'}).click();await second.getByRole('status').filter({hasText:'学习状态已保存'}).waitFor();await second.reload();
 const records=await second.evaluate(()=>JSON.parse(localStorage.getItem('ai-infra-lab.progress.v1')).records);assert.equal(records.computer.status,'submitted');assert.equal(records.arithmetic.evidence,'第二个标签页的未保存说明');await second.close();checks.push('two tabs preserve independent records and active draft');
 await page.goto(url+'/#learn');await page.getByRole('button',{name:'打开学习任务'}).click();
 await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='ai-infra-lab.progress.v1')throw new DOMException('storage full','QuotaExceededError');return original.call(this,k,v);};});
 await page.locator('#evidence').fill(evidence);await page.getByRole('button',{name:'提交成果记录'}).click();
 await page.locator('#storage-warning').filter({hasText:'尚未保存到浏览器'}).waitFor();
 assert.match(await page.locator('#storage-warning').innerText(),/尚未保存到浏览器/);assert.match(await page.locator('#notice').innerText(),/保存未成功/);checks.push('quota failure never displays a successful save');
 await page.reload();await page.evaluate(()=>localStorage.setItem('ai-infra-lab.progress.v1','{broken'));
 await page.reload();await page.getByRole('button',{name:'打开学习任务'}).click();await page.locator('#evidence').fill(evidence);await page.getByRole('button',{name:'提交成果记录'}).click();await page.getByRole('status').filter({hasText:'保存未成功'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('ai-infra-lab.progress.v1')),'{broken');checks.push('corrupt progress is not overwritten by normal save');
 await page.locator('#backup-file').setInputFiles('artifacts/qa-backup.json');await page.getByRole('status').filter({hasText:'合并恢复'}).waitFor();
 assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.startsWith('ai-infra-lab.progress.v1.recovery.')&&localStorage.getItem(k)==='{broken')),true);checks.push('explicit restore keeps original corrupt bytes');
 const catalog=JSON.parse(await readFile('site/catalog.json','utf8'));
 const large={schemaVersion:1,records:Object.fromEntries(catalog.nodes.map(n=>[n.id,{status:'started',evidence:'学'.repeat(6000),updatedAt:new Date(Date.now()+1000).toISOString()}]))};
 const buffer=Buffer.from(JSON.stringify(large,null,2));assert.ok(buffer.length>250000);
 await page.locator('#backup-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer});await page.getByRole('status').filter({hasText:'合并恢复'}).waitFor();
 await page.waitForFunction(()=>JSON.parse(localStorage.getItem('ai-infra-lab.progress.v1')).records.compiler?.evidence.length===6000);checks.push('valid backup exceeding old 250 KB limit restores');
 assert.deepEqual(errors,[]);await writeFile('artifacts/optimization-results.json',JSON.stringify({passed:true,checks},null,2));console.log(JSON.stringify({passed:true,checks},null,2));
}finally{await context.close();await browser.close();}
