// Maintainer utility: generate the first reviewed catalog; subsequent edits should target catalog.json.
import { writeFileSync,existsSync } from 'node:fs';
if(existsSync('site/catalog.json'))throw new Error('目录已存在，拒绝覆盖。请直接编辑并校验 catalog.json。');
const date='2026-10-08';
const sources=[
 ['cs50','CS50 Python','David J. Malan / Harvard','https://cs50.harvard.edu/python/','在线课程，审阅日期快照','en','CC BY-NC-SA 4.0','https://cs50.harvard.edu/python/license/','零基础','函数、分支、循环、异常、测试、文件处理','面向无经验学习者，作业与讲授相连','英文；部分外部平台可能需要账号','课程页面已访问；免费内容可直接阅读'],
 ['openstax','Prealgebra 2e','Lynn Marecek 等 / OpenStax','https://openstax.org/books/prealgebra-2e/pages/1-introduction','2e，在线页面快照','en','页面标示 CC BY-NC-SA；附加使用条款需逐项复核','https://openstax.org/books/prealgebra-2e/pages/1-introduction','无数学先修','算术与代数入门','允许数学基础不足者有明确起点','英文；不转载，不接入 AI 内容摄取','章节入口已访问'],
 ['missing','The Missing Semester','MIT Missing Semester 团队','https://missing.csail.mit.edu/','在线课程，审阅日期快照','en','待核实，仅链接','https://missing.csail.mit.edu/','文件与基本电脑操作','终端、Git、调试与开发工具','补齐课程通常默认已有的工程工具能力','Shell 教学以类 Unix 为主；Windows 需要单独指导','主页已访问'],
 ['missing-cn','计算机教育中缺失的一课','Missing Semester 中文翻译社区','https://missing-semester-cn.github.io/','中文社区在线版本','zh','待核实，仅链接','https://missing-semester-cn.github.io/','基本电脑操作','终端、Git 与工具中文辅助','降低英文阅读门槛；保留原课对照','社区译文；未逐句复核，不能标为官方翻译','主页已访问'],
 ['composing','Composing Programs','John DeNero','https://composingprograms.com/3ed/','第 3 版，部分章节仍在补充','en','CC BY-NC-SA 4.0','https://composingprograms.com/3ed/','Python 入门','抽象、递归、数据组织','以抽象和问题求解补充初学编程','第三版未完结，旧版可作补充','目录与许可声明已访问'],
 ['linear','MIT 18.06 线性代数','Gilbert Strang / MIT OCW','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/','Spring 2010','en','OCW 许可，以页面与材料例外为准','https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/','代数与函数','向量、矩阵、特征值、正定矩阵','有讲授、作业和考试，适合张量计算前置','只精选与 AI 系统相关章节；中文辅助待审校','课程目录已访问'],
 ['calculus','MIT 18.01SC 微积分','David Jerison / MIT OCW','https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/','Fall 2010','en','OCW 许可，以页面与材料例外为准','https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/','代数、函数','导数、链式法则、优化、积分','适合自学的分段结构与习题','多变量偏导仍需增补；不可把此课当完整梯度先修','课程目录已访问'],
 ['discrete','MIT 6.042J 计算机数学','MIT OCW 教学团队','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/','Spring 2015','en','OCW 许可，以页面与材料例外为准','https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/','基础代数','证明、离散结构与概率基础','支撑算法分析和随机性推理','不要求完整修完所有离散数学；概率统计覆盖仍需审计','课程入口已访问'],
 ['ostep','Operating Systems: Three Easy Pieces','Remzi H. Arpaci-Dusseau / Andrea C. Arpaci-Dusseau','https://pages.cs.wisc.edu/~remzi/OSTEP/','作者在线版本，未固定 PDF 修订号','en','待核实，仅链接；免费阅读不等于可转载','https://pages.cs.wisc.edu/~remzi/OSTEP/','C、数据结构与计算机组织','虚拟化、并发、持久化','围绕系统核心机制，配套项目值得深入评估','项目版本、运行环境和再分发授权未验证','作者主页已访问'],
 ['d2l','动手学深度学习','Aston Zhang / Zachary Lipton / Mu Li / Alexander Smola','https://zh.d2l.ai/','中文站 2.0.0 文档','zh','文字与代码分开授权；以仓库 LICENSE 为准','https://github.com/d2l-ai/d2l-zh/blob/master/LICENSE','Python、线性代数、微积分、概率','张量、自动微分、优化、模型训练','中文原始维护资源，结合代码与数学','旧依赖组合需复现；不能保证所有 Notebook 即开即用','中文目录和许可证入口已访问'],
 ['dlsys','Deep Learning Systems','CMU Deep Learning Systems 教学团队','https://dlsyscourse.org/','Fall 2026 课程页','en','待核实，仅链接','https://dlsyscourse.org/','系统编程、线性代数、微积分、概率、Python/C++、ML','自动微分、NDArray、CPU/CUDA 后端','Needle 作业提供从原理到实现的完整项目链','GPU 成本；mugrade/课程服务不保证校外可用','先修、目标和 HW0–HW4 描述已访问'],
 ['cs336','Stanford CS336','Percy Liang / Tatsunori Hashimoto / Stanford','https://cs336.stanford.edu/','Spring 2026 课程页','en','待核实，仅链接；作业仓库逐个核实','https://cs336.stanford.edu/','Python、深度学习与系统能力','语言模型、内核、并行、推理、数据与评估','资源核算和实际系统问题紧密关联','高阶材料；显存与算力要求必须逐作业标明','2026 教学日程已访问'],
 ['distributed','MIT 6.5840 分布式系统','MIT PDOS 教学团队','https://pdos.csail.mit.edu/6.5840/','Spring 2026','en','待核实，仅链接','https://pdos.csail.mit.edu/6.5840/','编程、操作系统、网络基础','容错与分布式系统实验','以真实故障语义支撑分布式训练的系统思维','Go 先修、各实验本地评测与许可仍待审查','课程主页已访问'],
 ['cuda','CUDA Programming Guide','NVIDIA','https://docs.nvidia.com/cuda/cuda-programming-guide/','滚动文档，未固定 CUDA 版本','en','厂商文档条款；仅链接','https://docs.nvidia.com/cuda/cuda-programming-guide/','C/C++、体系结构和并发','GPU 执行、内存与并行编程','硬件编程的一手依据','必须固定工具链、驱动与硬件；本次未安装 CUDA','官方目录已访问'],
 ['torch','PyTorch Distributed','PyTorch contributors','https://docs.pytorch.org/docs/stable/distributed.html','stable 滚动文档，具体发行版待锁定','en','待逐项核实文档许可，仅链接','https://docs.pytorch.org/docs/stable/distributed.html','PyTorch、进程、网络和并行算法','通信与分布式训练','生产框架官方 API 作为实现对照','这里只验证入口重定向，未验证多卡程序','入口可访问，正文深审待完成'],
 ['vllm','vLLM','vLLM project contributors','https://docs.vllm.ai/en/latest/','latest 滚动文档，发行版待锁定','en','待核实文档与代码各自许可，仅链接','https://docs.vllm.ai/en/latest/','模型推理、GPU 与服务基础','高吞吐推理与部署','工业系统用于验证性能和部署能力','不是零基础教材；模型许可及硬件需求必须单独核查','官方文档入口已访问'],
 ['mlsys','Machine Learning Systems','Harvard MLSysBook 教学团队','https://mlsysbook.ai/','站点标示 2026 双卷版本','en','站点标示 CC BY-NC-SA 4.0；各工具单独核查','https://mlsysbook.ai/','编程和 ML 基础','从单机到规模化系统，伴随 TinyTorch 与实验','用于交叉检查系统能力边界与遗漏','不把教材的完整性宣称作为本项目已验证事实','总览、目录入口与许可页脚已访问'],
 ['security','Kubernetes Security','Kubernetes contributors','https://kubernetes.io/docs/concepts/security/','官方滚动文档','en','待核实，仅链接','https://kubernetes.io/docs/concepts/security/','网络、操作系统与部署基础','基础设施权限与安全隔离','补充只关注性能的路线容易漏掉的运维能力','进阶分支；零基础不先装集群','官方安全文档入口已访问']
].map(([id,title,author,url,version,language,license,licenseUrl,prerequisites,coverage,reason,limitations,verification])=>({id,title,author,url,version,language,license,licenseUrl,prerequisites,coverage,reason,limitations,verification,reviewedAt:date,reviewLevel:'初步桌面审阅，未完成教学效果或环境复现验证',reuse:'仅链接与原创简短导读，不镜像、不转载',evaluation:{authority:'作者 / 大学 / 项目官方来源；社区翻译单独标示',accuracy:'材料入口已核对，内容未逐章审校',depth:coverage,engineeringValue:reason,coverage,teachingQuality:'根据目录与作业结构初审，学习者试用待完成',difficulty:prerequisites,languageFriendliness:language==='zh'?'中文；术语及具体代码仍需复核':'英文，中文导读可用；完整译文未提供',accessibility:verification,maintenance:version,licensing:license,stability:'可变在线资源；正式实验集成前固定版本或 commit'}}));
const stages=[{id:0,title:'起点 · 电脑与第一行代码',description:'从文件、数字和函数开始'},{id:1,title:'基础 · 数学与程序设计',description:'建立推理和实现能力'},{id:2,title:'系统 · 理解计算机',description:'从内存、并发到网络'},{id:3,title:'模型 · 搭建学习系统',description:'张量、梯度与训练框架'},{id:4,title:'工程 · 加速与规模化',description:'GPU、分布式、推理与可靠性'}];
const rows=[
 ['computer','认识文件与运行程序',0,[],['cs50'],'core','找到文件、分清编辑器与终端，运行一次程序','创建学习文件夹；在 CS50 官方浏览器环境中运行输出，不要求先装开发工具。','截图与运行步骤；说明文件路径与程序输出的区别'],
 ['arithmetic','数字、比例与算术',0,[],['openstax'],'core','理解整数、小数、分数、比例和单位','按需学习四则运算、分数、小数与比例；能读懂时间和容量单位。','独立计算吞吐量、容量单位与百分比，并解释步骤'],
 ['python','第一段 Python 程序',0,['computer'],['cs50'],'core','掌握输入输出、变量、字符串和函数','完成 CS50 Python 第 0 周；尝试 Indoor Voice，再进入分支和循环。','通过本地 Indoor Voice 检查，提交代码并解释 lower() 的行为'],
 ['tools','终端、Git 与可复现环境',1,['computer','python'],['missing','missing-cn'],'core','保存版本、定位错误并复现运行步骤','学习 shell、版本控制、调试章节；Windows 先用 PowerShell，类 Unix 命令按原课环境运行。','提交 Git 历史、一次错误定位记录与可复现 README'],
 ['algebra','代数、函数与指数',1,['arithmetic'],['openstax'],'core','理解变量、方程、函数图像和指数','前代数教材只是起点；函数与对数的后续主资源仍待补齐，不要把读完教材标为所有先修已完成。','推导一个内存容量公式，画函数图并解释指数增长'],
 ['programming','抽象、递归与测试',1,['python'],['composing','cs50'],'core','将需求拆解为函数与可测试程序','学习递归、序列和数据抽象；CS50 后续作业提供练习。','提交 CS50 Final Project 或相当项目，含边界测试与设计解释'],
 ['discrete','证明与离散结构',1,['algebra','programming'],['discrete'],'core','理解不变量、集合、图与归纳证明','精选证明、图与离散结构，不强制完整修完所有章节。','为算法写循环不变量与证明；构建并检测一个有向图的环'],
 ['linear','向量、矩阵与线性代数',1,['algebra'],['linear'],'core','理解线性变换、矩阵乘法和特征值','精选向量空间、线性方程、正交与特征值；连接到张量维度。','独立完成选定原课习题并解释矩阵乘法形状'],
 ['calculus','导数与梯度',1,['algebra'],['calculus'],'core','理解导数、链式法则和优化','单变量微积分先行；多变量偏导与梯度资源补齐前保留缺口。','手算链式法则，做有限差分检查并说明误差'],
 ['probability','概率与统计推理',1,['algebra','discrete'],['discrete'],'core','理解随机变量、期望、方差与实验置信度','6.042J 用于概率起点；统计推断主资源仍待选定。','模拟抽样并报告方差；说明单次 benchmark 为什么不充分'],
 ['algorithms','数据结构与复杂度',2,['programming','discrete'],['composing'],'core','选择数据结构，分析时间和空间成本','现有主资源只覆盖部分数据抽象；完整算法课程待比较。','实现并测量不同索引方案，解释规模增长与复杂度'],
 ['architecture','C/C++、内存与计算机组织',2,['programming','tools','arithmetic'],['ostep','cuda'],'core','理解地址、缓存、指针和编译流程','现有资源为后续依据；初学 C 与计算机组织主课缺失，暂不宣称可直接衔接。','分析缓存行为，检查越界并解释编译与链接'],
 ['os','操作系统与并发',2,['architecture','algorithms'],['ostep'],'core','理解进程、虚拟内存、同步与持久化','按 OSTEP 核心主题学习；在已有项目中复现竞态与修复。','提交竞态复现、同步正确性测试和持久化故障分析'],
 ['network','网络与存储 I/O',2,['os'],['distributed'],'core','分析通信延迟、带宽和存储成本','分布式课只是需求依据；网络入门主资源仍待筛选。','解释一次请求的路径并测量 I/O 与网络瓶颈'],
 ['numerics','数值稳定性与性能测量',3,['linear','calculus','probability','architecture'],['d2l','dlsys'],'core','判断精度、溢出和测量误差','学习稳定 softmax、有限差分及 dtype；记录硬件、预热和重复测量。','比较数值误差和性能分布，报告精度容差与实验条件'],
 ['ml','机器学习与优化基础',3,['programming','linear','calculus','probability'],['d2l'],'core','理解训练、损失、优化与泛化','学习线性模型、梯度下降和训练评估，明确训练/测试数据边界。','训练并评估基线，解释数据泄漏和过拟合'],
 ['framework','张量、自动微分与框架',3,['ml','numerics','os'],['dlsys'],'core','实现并测试一个教学深度学习框架','循序推进 Needle HW0–HW4；原作业与测试许可及校外运行方式仍待复现。','梯度与参考结果对比；算子、优化器测试与设计文档'],
 ['data','数据管线与可复现训练',3,['ml','tools','network'],['cs336','mlsys'],'core','追踪数据来源、处理吞吐与实验版本','学习去重、过滤、加载与评估；记录数据许可和随机种子。','提交数据来源清单、复现记录及加载瓶颈分析'],
 ['gpu','GPU 内核与性能工程',4,['framework','architecture','numerics'],['cuda','cs336'],'specialist','分析算力与带宽瓶颈，优化算子','先验证结果，再做 tiling 等优化；硬件不可用时只学习理论，不标为实验通过。','正确性容差、参考实现、重复测量与性能分析报告'],
 ['dist','分布式与故障恢复',4,['os','network','algorithms'],['distributed'],'specialist','理解复制、协调、故障和一致性','使用 6.5840 原实验；Go 前置与本地评测路径尚未集成。','故障注入、恢复测试与一致性解释'],
 ['training','分布式训练系统',4,['framework','data','gpu','dist'],['torch','cs336'],'specialist','比较数据、张量和流水线并行','先单机建立基线，再进行通信与显存分析。','扩展效率、通信剖析、断点恢复和训练结果一致性'],
 ['inference','推理服务与性能',4,['framework','gpu','network','data'],['vllm','cs336'],'specialist','理解批处理、缓存、延迟与吞吐权衡','用官方系统建立基线；模型大小、授权与 GPU 成本在实验前确认。','报告 TTFT、逐 token 延迟、吞吐、显存与结果正确性'],
 ['operations','可靠性、安全与可观测性',4,['os','network','tools'],['security','mlsys'],'core','定位系统故障、限制权限并准备回滚','从日志、指标和最小权限开始；集群部署是后续分支。','故障定位、权限说明、恢复演练与成本记录'],
 ['compiler','编译器与算子图优化',4,['architecture','algorithms','framework'],['cs336','dlsys'],'optional','理解图转换、融合和编译约束','资源覆盖不足；编译器原理、MLIR/Triton 教学资源需要独立调研。','语义等价测试、编译时间与性能权衡报告']
];
const nodes=rows.map(([id,title,stage,prerequisites,resources,category,objective,guidance,evidence])=>({id,title,stage,prerequisites,resources,category,objective,guidance,evidence,status:['algebra','calculus','probability','algorithms','architecture','network','compiler'].includes(id)?'前置或主资源待补齐':'初步映射，教学衔接待验证'}));
const labs=[
 {id:'indoor',title:'入门验收 · Indoor Voice',stage:0,nodes:['python'],source:'cs50',url:'https://cs50.harvard.edu/python/2022/psets/0/indoor/',hardware:'普通 CPU；本地检查需要 Python 3.10+ 和 Node 22+',status:'本地补充检查可用；不是阶段综合项目',goal:'依据原题要求独立实现字符串小写转换，学会运行程序、测试和解释结果。',rubric:['遵照原题自行编写 indoor.py，保留原作者与题目链接','覆盖混合大小写、数字与标点、中文、空输入','用本地检查器检测输出；阅读失败反馈后修复','解释输入、处理、输出与测试局限；保留运行记录'],command:'node scripts/grade.mjs ./indoor.py python',limitation:'补充检查不是原课程官方评分，不证明整个编程阶段已掌握。运行学习者代码只在主动执行 CLI 后发生；超时不等于安全沙箱。'},
 {id:'python-project',title:'程序设计 · CS50 Python Final Project',stage:1,nodes:['programming','tools'],source:'cs50',url:'https://cs50.harvard.edu/python/project/',hardware:'CPU / Python；依项目需求',status:'精选候选；完整本地验收待集成',goal:'完成有实际用途的独立程序，呈现设计、测试与说明。',rubric:['依据原课项目要求自行设计实现','提交 README 与依赖说明','正确性、边界情况与失败处理测试','解释设计选择，不能用复制代码代替独立实现'],limitation:'原课程账号、提交与评分服务不是本平台能力；许可证与依赖需要在引入具体代码时核实。'},
 {id:'ostep-project',title:'计算系统 · OSTEP Projects',stage:2,nodes:['os','tools'],source:'ostep',url:'https://pages.cs.wisc.edu/~remzi/OSTEP/',hardware:'CPU / C 工具链；原项目环境待验证',status:'作者提供项目入口；未完成项目级选型',goal:'从原作者的项目中评估适合本路线的并发、虚拟化或持久化实验。',rubric:['先锁定项目与 commit，再确认许可','记录运行条件、正确性与竞态测试','测量性能并复现故障','提交原理与设计解释'],limitation:'尚未选定可独立运行的具体项目，不显示为已集成实验。'},
 {id:'needle',title:'学习框架 · Needle HW0–HW4',stage:3,nodes:['framework'],source:'dlsys',url:'https://dlsyscourse.org/',hardware:'Python/C++；部分阶段需要兼容 CUDA GPU',status:'课程描述已核对；本地复现待完成',goal:'沿原课作业实现自动微分、模块与 NDArray 后端。',rubric:['遵从原课程代码及作业许可','梯度和算子正确性测试','CPU/GPU 对照与数值误差说明','性能报告与框架设计文档'],limitation:'课程 mugrade 服务不保证校外可用；尚未提供已验证的环境锁文件。'},
 {id:'systems',title:'语言模型系统 · CS336 系统作业',stage:4,nodes:['gpu','training'],source:'cs336',url:'https://cs336.stanford.edu/',hardware:'按原作业确认 GPU 显存与算力预算',status:'课程日程已核对；实验环境未复现',goal:'从原课内核和并行主题入手，训练系统优化与解释能力。',rubric:['固定原作业版本、硬件与依赖','记录参考正确性、容差与基线','重复测量并分析瓶颈','解释优化原因与失败边界'],limitation:'多卡与 GPU 检查未执行；不能以提交记录代替实际结果。'},
 {id:'raft',title:'分布式系统 · 6.5840 原实验',stage:4,nodes:['dist'],source:'distributed',url:'https://pdos.csail.mit.edu/6.5840/',hardware:'CPU / Go；原实验环境待验证',status:'精选候选；Go 前置与本地验收待集成',goal:'通过原课程实验理解容错语义与故障恢复。',rubric:['核实原实验版本与许可证','先验证 Go 与并发先修','按原测试进行故障注入','提交正确性、恢复行为与设计解释'],limitation:'不重新生成一套替代原实验；独立复现后再标记已集成。'}
];
writeFileSync('site/catalog.json',JSON.stringify({schemaVersion:1,reviewedAt:date,stages,sources,nodes,labs},null,2)+'\n');
