import {readFileSync,writeFileSync,existsSync} from 'node:fs';
if(existsSync('site/views.js'))throw new Error('Views have already been extracted.');
let app=readFileSync('site/app.js','utf8');
const escape=app.slice(app.indexOf('const escape='),app.indexOf('\nlet catalog'));
const helpers=app.slice(app.indexOf('const source='),app.indexOf('function storageWarning'));
const start=app.indexOf('function intro('),end=app.indexOf('const views={learn:learning,map,resources,labs,about};');
let views=app.slice(start,end);
views=views.replace('<strong>01</strong><span>已提供本地补充检查的入门练习</span>','<strong>${String(catalog.labs.filter(l=>l.command).length).padStart(2,"0")}</strong><span>提供本地运行流程的实验</span>');
views=views.replace('<p class="muted">${escape(n.guidance)}</p>','<p class="muted">${escape(n.guidance)}</p><ol class="steps">${(n.steps||[]).map(s=>`<li>${escape(s.task)}</li>`).join(\'\')}</ol>');
views=views.replace('<h3>用成果说明掌握情况</h3>','${catalog.labs.some(l=>l.nodes.includes(n.id))?`<h3>相关实践</h3><ul class="steps">${catalog.labs.filter(l=>l.nodes.includes(n.id)).map(l=>`<li>${link(l.guide||l.url,l.title)} · ${escape(l.status)}</li>`).join(\'\')}</ul>`:\'\'}<h3>用成果说明掌握情况</h3>');
views=views.replace('只有入门练习提供本地补充检查，高级实验的环境与完整评测仍待集成。','入门练习与对象运行时项目已提供本地运行流程；其余候选的具体条件与验证状态逐项列明。');
views=views.replace("link('./docs/getting-started.md','阅读本地实验指南')","link(l.guide||'./docs/getting-started.md','阅读本地实验指南')");
views=views.replace('多变量微积分、统计推断、完整算法、C/计算机组织和网络主课；GPU/多卡实测；跨平台实验复现；中文导读审校。','基础主课与选读任务已补充；仍需长期试学、GPU/多卡复现、中文逐项审校及独立作品评审。');
writeFileSync('site/views.js',`import {ready,nextNode} from './core.js';\n${escape}\n\nexport function createViews(state){\nconst {catalog,progress,selected,filter,stageFilter,langFilter,drafts}=state;\n${helpers}\n${views}\nreturn {learn:learning,map,resources,labs,about};\n}\n`);
app=app.slice(0,start)+app.slice(end);
app=app.replace(helpers,'');
app="import {createViews} from './views.js';\n"+app;
app=app.replace('const views={learn:learning,map,resources,labs,about};','');
app=app.replace('function render(){','function render(){const views=createViews({catalog,progress,selected,filter,stageFilter,langFilter,drafts});');
writeFileSync('site/app.js',app);
